apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yaml
  - bootstrapping-ca-issuers.yaml
  - letsencrypt.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
